### ISSUE TITLE
snmpset not work

### ISSUE THREAD

**Issue by kshyshkin** [leandroadonis86/esp32_simple_snmpv2c_agent#1]
Hello. Thank you for your implementation snmp agent. Try to up your example, and get a problem. When i try get value:
```snmpget -v 2c -c public 192.168.1.33 1.3.6.1.4.1.26381.1.1.0``` all ok, i get ```iso.3.6.1.4.1.26381.1.1.0 = INTEGER: 0```

But when i try ```snmpset -v 2c -c public 192.168.1.33 1.3.6.1.4.1.26381.1.1.0 i 1```
i get ```Timeout: No Response from 192.168.1.33```

From your exammple i only change wifi settings for my wifi, and address of server, put it by ip of my computer. Have you any idea why i cant set value?

**Comment by leandroadonis86** [comment]
Greetings, No problem. File my_mib.c, my_mib.h and simple_snmp_agent.c must be edited for set snmp. SET not implemented yet since I still don't have time lately, anyway is simple to implement.

my_mib.c need:
1. function prototype for s"et_integer_value" for example
2. "static const struct", with mib id you want
3. refer it on pointer "snmp_node*"
4. implement protoptype to set integer in pointer (following "static snmp_err_t" as an function example)

File my_mib.h: 
1. add extern to make your pointer visible between simple_agent*.c and my_mib.c

File esp32_simple_snmpv2c_agent.c 
1. function "static void initialize_gpio" make it get value from the pointer and print to console and make it suitable for your needs.

**Comment by kshyshkin** [comment]
Thank you for your reply. I dont know why you write that you not implement set function. It realize in your code. May be you forget :) Problem was slowed. I need only change ```public``` on ```private``` in request, because in snmp opt default community for set is private.

**Comment by MNRaza** [comment]
Hello Sir,
I'm also facing same issue with SET command.
I already changed "private" to "public" in snmp_msg.c file.
But still unable to set value.

Please look into my code where I'm wrong? 
`/* control_mode value .1.3.6.1.4.1.1206.4.2.3.6.1.0 */
u32_t control_mode =1;
static s16_t get_dmsControlMode_value(struct snmp_node_instance* instance, void* value)
{
	u32_t *uint_ptr = (u32_t*) value;
	*uint_ptr = (u32_t) control_mode;
	return sizeof(*uint_ptr);
}
static snmp_err_t set_dmsControlMode_value(struct snmp_node_instance* instance, u16_t len, void *value)
{
	control_mode = *((u32_t*)value);
	return SNMP_ERR_NOERROR;
}
static const struct snmp_scalar_node dmsControlMode_node = SNMP_SCALAR_CREATE_NODE(1, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, get_dmsControlMode_value, NULL, set_dmsControlMode_value); //read-and-write example

static const struct snmp_node* const dmsControlMode_nodes[] = {&dmsControlMode_node.node.node };
static const struct snmp_tree_node dmsControlMode_tree_node = SNMP_CREATE_TREE_NODE(6, dmsControlMode_nodes);

/* define private mib */
static const u32_t dmsControlMode_base_oid[] = { 1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 6, };
const struct snmp_mib dmsControlMode_mib = SNMP_MIB_CREATE(dmsControlMode_base_oid, &dmsControlMode_tree_node.node);`
